lang: ru

webserver:
  web-port: 8085
  alternative-Ip:
    enabled: false # Automatically detected if false

    address: your.domain.here

discord-integration:
  token: "YOUR-TOKEN"

faction-settings:
  max-members: 10
  invite-cooldown-seconds: 60